apiVersion: v1
kind: Namespace
metadata:
  name: jeongdo
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-my-app
  namespace: jeongdo
data:
  .dockerconfigjson: <NHN Container Registry(NCR) 접근 인증 관련 base64인코딩 데이터>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-credentials
  namespace: jeongdo
type: Opaque
data:
  ACCESS_KEY_ID: <Access key ID의 base64인코딩 데이터>
  SECRET_ACCESS_KEY: <Secret access key의 base64인코딩 데이터>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: jeongdo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 3973255b-kr1-registry.container.nhncloud.com/my_app/defact0/my_boto3_app:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: my-app-credentials
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: secret-my-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: jeongdo
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
